# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BarcodeSeqKit',
                'doc_host': 'https://mtinti.github.io',
                'git_url': 'https://github.com/mtinti/BarcodeSeqKit',
                'lib_path': 'BarcodeSeqKit'},
  'syms': {'BarcodeSeqKit.core': {'BarcodeSeqKit.core.foo': ('core.html#foo', 'BarcodeSeqKit/core.py')}}}
